/**
 * UI検索だけで使う読み仮名・通称。
 * crawlerのアーティスト自動判定に使うArtist.keywordsとは分離し、短い愛称を追加しても
 * 取得データの誤紐付けを起こさないようにする。
 */
export const ARTIST_SEARCH_ALIASES: Readonly<Record<string, readonly string[]>> = {
  nogizaka46: ["ノギザカ46", "ノギザカ"],
  sakurazaka46: ["サクラザカ46", "サクラザカ"],
  hinatazaka46: ["ヒナタザカ46", "ヒナタザカ"],
  "stray-kids": ["ストレイキッズ"],
  seventeen: ["セブンティーン"],
  acees: ["エイシーズ"],
  fantastics: ["ファンタスティックス"],
  "me-i": ["ミーアイ"],
  roselia: ["ロゼリア"],
  treasure: ["トレジャー"],
  news: ["ニュース"],
  "hiromitsu-kitayama": ["キタヤマヒロミツ"],
  "cutie-street": ["キューティーストリート", "キュースト"],
  "ballistik-boyz": ["バリスティックボーイズ", "バリボ"],
  generations: ["ジェネレーションズ", "ジェネ"],
  shinee: ["シャイニー"],
  team: ["エンティーム"],
  "shigure-ui": ["シグレウイ"],
  "g-i-dle": ["ジーアイドゥル", "アイドゥル"],
  joy: ["ニアリーイコールジョイ", "ニアジョイ"],
  "le-sserafim": ["ルセラフィム", "ルセラ"],
  "king-prince": ["キングアンドプリンス", "キンプリ"],
  arashi: ["アラシ"],
  "ryosuke-yamada": ["ヤマダリョウスケ"],
  "j-soul-brothers": ["サンダイメジェイソウルブラザーズ", "サンダイメ"],
  buddiis: ["バディーズ"],
  "the-rampage": ["ザランページ", "ランペ"],
  timelesz: ["タイムレス"],
  "kis-my-ft2": ["キスマイフットツー", "キスマイ"],
  ado: ["アド"],
  aespa: ["エスパ"],
  exo: ["エクソ"],
  nexz: ["ネクスジ"],
  "number-i": ["ナンバーアイ"],
  yoasobi: ["ヨアソビ"],
  bigbang: ["ビッグバン"],
  "juice-juice": ["ジュースジュース"],
  "alpha-drive-one": ["アルファドライブワン"],
  "lilas-ikuta": ["イクタリラ"],
  holox: ["ヒミツケッシャホロックス", "ホロックス"],
  bts: ["ビーティーエス", "バンタン"],
  ini: ["アイエヌアイ"],
  newjeans: ["ニュージーンズ"],
  jo1: ["ジェイオーワン"],
  "2pm": ["トゥーピーエム"],
  ive: ["アイヴ"],
  "bullet-train": ["チョウトッキュウ"],
  enhypen: ["エンハイプン", "エナプ"],
  "be-first": ["ビーファースト"],
  "da-ice": ["ダイス"],
  "kento-nakajima": ["ナカジマケント"],
  "m-lk": ["ミルク"],
  "momosuzu-nene": ["モモスズネネ"],
  "doh-kyung-soo-d-o": ["ドギョンス", "ディオ"],
  "candy-tune": ["キャンディーチューン", "キャンチュー"],
  beyooooonds: ["ビヨーンズ"],
  mazzel: ["マーゼル"],
  riize: ["ライズ"],
  "kat-tun": ["カトゥーン"],
  "one-ok-rock": ["ワンオクロック", "ワンオク"],
  "back-number": ["バックナンバー"],
  "mrs-green-apple": ["ミセスグリーンアップル", "ミセス"],
  officialdism: ["オフィシャルヒゲダンディズム", "ヒゲダン"],
  and2ble: ["アンダブル"],
  "fujii-kaze": ["フジイカゼ"],
  ateez: ["エイティーズ"],
  "nct-wish": ["エヌシーティーウィッシュ"],
  nmixx: ["エンミックス"],
  babymonster: ["ベイビーモンスター", "ベビモン"],
  tws: ["トゥアス"],
  illit: ["アイリット"],
  zerobaseone: ["ゼロベースワン", "ゼベワン"],
  itzy: ["イッチ"],
  "tomorrow-x-together": ["トゥモローバイトゥギャザー", "トゥバ"],
  "nct-dream": ["エヌシーティードリーム", "ドリム"],
  blackpink: ["ブラックピンク", "ブルピン"],
  twice: ["トゥワイス"],
  boynextdoor: ["ボーイネクストドア", "ボネクド"],
  ikon: ["アイコン"],
  "travis-japan": ["トラビスジャパン", "トラジャ"],
  imp: ["アイエムピー"],
  domoto: ["ドウモト"],
  roirom: ["ロイロム"],
};
